### ISSUE TITLE
Making scripts executable?

### ISSUE THREAD

**Issue by alyxazon** [GSI-CS-CO/wrs_config#1]
Could we make the python scripts "directly" executable?

Current usage: python do_generate_config.py switches.json

Future usage: ./do_generate_config.py switches.json

1. #!/usr/bin/env python <- Add this to every script (shebang)
2. chmod +x every py file and commit git :)

**Comment by ebold-cscotos** [comment]
sure, nice idea -> done in commit 027ab5d
